interface CountryPattern {
  code: string;
  name: string;
  nameJp: string;
  pattern: RegExp;
}

// Sorted by name ASC. Detection uses earliest match position, so array order does not affect results.
const COUNTRY_PATTERNS: CountryPattern[] = [
  {
    code: 'AFG',
    name: 'Afghanistan',
    nameJp: 'アフガニスタン',
    pattern: /\b(afghani(?:stan)?)\b/i,
  },
  { code: 'ALB', name: 'Albania', nameJp: 'アルバニア', pattern: /\b(albania[n]?)\b/i },
  { code: 'DZA', name: 'Algeria', nameJp: 'アルジェリア', pattern: /\b(algeri[a]?(?:an)?)\b/i },
  { code: 'AGO', name: 'Angola', nameJp: 'アンゴラ', pattern: /\b(angol[a]?(?:an)?)\b/i },
  {
    code: 'ATG',
    name: 'Antigua and Barbuda',
    nameJp: 'アンティグア・バーブーダ',
    pattern: /\b(antigua(?:\s+and\s+barbuda)?)\b/i,
  },
  { code: 'ARG', name: 'Argentina', nameJp: 'アルゼンチン', pattern: /\b(argentin[ae](?:an)?)\b/i },
  { code: 'ARM', name: 'Armenia', nameJp: 'アルメニア', pattern: /\b(armeni[a]?(?:an)?)\b/i },
  {
    code: 'AUS',
    name: 'Australia',
    nameJp: 'オーストラリア',
    pattern: /\b(australia[n]?|aussie[s]?|oz)\b/i,
  },
  {
    code: 'AUT',
    name: 'Austria',
    nameJp: 'オーストリア',
    pattern: /\b(austria[n]?|österreich)\b/i,
  },
  {
    code: 'AZE',
    name: 'Azerbaijan',
    nameJp: 'アゼルバイジャン',
    pattern: /\b(azerbaija[n]?(?:i)?)\b/i,
  },
  { code: 'BHS', name: 'Bahamas', nameJp: 'バハマ', pattern: /\b(bahama[s]?(?:ian)?)\b/i },
  { code: 'BHR', name: 'Bahrain', nameJp: 'バーレーン', pattern: /\b(bahrain(?:i)?)\b/i },
  {
    code: 'BGD',
    name: 'Bangladesh',
    nameJp: 'バングラデシュ',
    pattern: /\b(banglades[h]?(?:i)?)\b/i,
  },
  { code: 'BRB', name: 'Barbados', nameJp: 'バルバドス', pattern: /\b(barbad(?:os|ian))\b/i },
  {
    code: 'BLR',
    name: 'Belarus',
    nameJp: 'ベラルーシ',
    pattern: /\b(belarus(?:ian)?|belorussia)\b/i,
  },
  { code: 'BEL', name: 'Belgium', nameJp: 'ベルギー', pattern: /\b(belgi(?:um|an|que))\b/i },
  { code: 'BLZ', name: 'Belize', nameJp: 'ベリーズ', pattern: /\b(beliz[e]?(?:an)?)\b/i },
  { code: 'BEN', name: 'Benin', nameJp: 'ベナン', pattern: /\b(benin(?:ese)?)\b/i },
  { code: 'BTN', name: 'Bhutan', nameJp: 'ブータン', pattern: /\b(bhutan(?:ese)?)\b/i },
  { code: 'BOL', name: 'Bolivia', nameJp: 'ボリビア', pattern: /\b(bolivia[n]?)\b/i },
  {
    code: 'BIH',
    name: 'Bosnia and Herzegovina',
    nameJp: 'ボスニア・ヘルツェゴビナ',
    pattern: /\b(bosnia(?:\s+and\s+herzegovina)?|bosnian)\b/i,
  },
  { code: 'BWA', name: 'Botswana', nameJp: 'ボツワナ', pattern: /\b(botswan[a]?(?:an)?)\b/i },
  { code: 'BRA', name: 'Brazil', nameJp: 'ブラジル', pattern: /\b(brazil(?:ian)?|brasil)\b/i },
  { code: 'BRN', name: 'Brunei', nameJp: 'ブルネイ', pattern: /\b(brunei(?:an)?)\b/i },
  { code: 'BGR', name: 'Bulgaria', nameJp: 'ブルガリア', pattern: /\b(bulgari[a]?(?:an)?)\b/i },
  {
    code: 'BFA',
    name: 'Burkina Faso',
    nameJp: 'ブルキナファソ',
    pattern: /\b(burkina\s+faso|burkinab[eé])\b/i,
  },
  { code: 'BDI', name: 'Burundi', nameJp: 'ブルンジ', pattern: /\b(burund[i]?(?:an)?)\b/i },
  { code: 'KHM', name: 'Cambodia', nameJp: 'カンボジア', pattern: /\b(cambodia[n]?|khmer)\b/i },
  { code: 'CMR', name: 'Cameroon', nameJp: 'カメルーン', pattern: /\b(cameroo[n]?(?:ian)?)\b/i },
  { code: 'CAN', name: 'Canada', nameJp: 'カナダ', pattern: /\b(canada[n]?|canuck[s]?)\b/i },
  {
    code: 'CPV',
    name: 'Cape Verde',
    nameJp: 'カーボベルデ',
    pattern: /\b(cape\s+verde|cabo\s+verde)\b/i,
  },
  {
    code: 'CAF',
    name: 'Central African Republic',
    nameJp: '中央アフリカ共和国',
    pattern: /\b(central\s+african\s+republic)\b/i,
  },
  { code: 'TCD', name: 'Chad', nameJp: 'チャド', pattern: /\b(chad(?:ian)?)\b/i },
  { code: 'CHL', name: 'Chile', nameJp: 'チリ', pattern: /\b(chile(?:an)?)\b/i },
  { code: 'CHN', name: 'China', nameJp: '中国', pattern: /\b(chin[a]?(?:ese)?|prc|中国)\b/i },
  { code: 'COL', name: 'Colombia', nameJp: 'コロンビア', pattern: /\b(colombia[n]?)\b/i },
  { code: 'COM', name: 'Comoros', nameJp: 'コモロ', pattern: /\b(comoros|comorian)\b/i },
  { code: 'CRI', name: 'Costa Rica', nameJp: 'コスタリカ', pattern: /\b(costa\s+rica[n]?)\b/i },
  {
    code: 'CIV',
    name: "Côte d'Ivoire",
    nameJp: 'コートジボワール',
    pattern: /\b(ivory\s+coast|c[oô]te\s+d'ivoire)\b/i,
  },
  { code: 'HRV', name: 'Croatia', nameJp: 'クロアチア', pattern: /\b(croatia[n]?|hrvatska)\b/i },
  { code: 'CUB', name: 'Cuba', nameJp: 'キューバ', pattern: /\b(cuba[n]?)\b/i },
  { code: 'CYP', name: 'Cyprus', nameJp: 'キプロス', pattern: /\b(cypru[s]?(?:iot)?)\b/i },
  {
    code: 'CZE',
    name: 'Czechia',
    nameJp: 'チェコ',
    pattern: /\b(czech(?:\s+republic)?|czechia)\b/i,
  },
  { code: 'DNK', name: 'Denmark', nameJp: 'デンマーク', pattern: /\b(denm(?:ark|arks)|danish)\b/i },
  { code: 'DJI', name: 'Djibouti', nameJp: 'ジブチ', pattern: /\b(djibouti(?:an)?)\b/i },
  { code: 'DMA', name: 'Dominica', nameJp: 'ドミニカ国', pattern: /\b(dominica[n]?)\b/i },
  {
    code: 'DOM',
    name: 'Dominican Republic',
    nameJp: 'ドミニカ共和国',
    pattern: /\b(dominican\s+republic)\b/i,
  },
  {
    code: 'COD',
    name: 'DR Congo',
    nameJp: 'コンゴ民主共和国',
    pattern: /\b(democratic\s+republic\s+of\s+(?:the\s+)?congo|dr\s+congo|drc)\b/i,
  },
  { code: 'ECU', name: 'Ecuador', nameJp: 'エクアドル', pattern: /\b(ecuador(?:ian)?)\b/i },
  { code: 'EGY', name: 'Egypt', nameJp: 'エジプト', pattern: /\b(egypt(?:ian)?)\b/i },
  {
    code: 'SLV',
    name: 'El Salvador',
    nameJp: 'エルサルバドル',
    pattern: /\b(el\s+salvador(?:an)?)\b/i,
  },
  {
    code: 'GNQ',
    name: 'Equatorial Guinea',
    nameJp: '赤道ギニア',
    pattern: /\b(equatorial\s+guinea)\b/i,
  },
  { code: 'ERI', name: 'Eritrea', nameJp: 'エリトリア', pattern: /\b(eritre[a]?(?:an)?)\b/i },
  { code: 'EST', name: 'Estonia', nameJp: 'エストニア', pattern: /\b(estonia[n]?)\b/i },
  { code: 'SWZ', name: 'Eswatini', nameJp: 'エスワティニ', pattern: /\b(eswatini|swaziland)\b/i },
  { code: 'ETH', name: 'Ethiopia', nameJp: 'エチオピア', pattern: /\b(ethiopi[a]?(?:an)?)\b/i },
  { code: 'FJI', name: 'Fiji', nameJp: 'フィジー', pattern: /\b(fiji(?:an)?)\b/i },
  { code: 'FIN', name: 'Finland', nameJp: 'フィンランド', pattern: /\b(finland|finnish|suomi)\b/i },
  { code: 'FRA', name: 'France', nameJp: 'フランス', pattern: /\b(france|french)\b/i },
  {
    code: 'PYF',
    name: 'French Polynesia',
    nameJp: 'フランス領ポリネシア',
    pattern: /\b(french\s+polynesi[a]?(?:an)?|tahiti(?:an)?)\b/i,
  },
  { code: 'GAB', name: 'Gabon', nameJp: 'ガボン', pattern: /\b(gabon(?:ese)?)\b/i },
  { code: 'GMB', name: 'Gambia', nameJp: 'ガンビア', pattern: /\b(gambi[a]?(?:an)?)\b/i },
  { code: 'GEO', name: 'Georgia', nameJp: 'ジョージア', pattern: /\b(georgi[a]?(?:an)?)\b/i },
  { code: 'DEU', name: 'Germany', nameJp: 'ドイツ', pattern: /\b(german[y]?|deutschland)\b/i },
  { code: 'GHA', name: 'Ghana', nameJp: 'ガーナ', pattern: /\b(ghan[a]?(?:aian)?)\b/i },
  { code: 'GRC', name: 'Greece', nameJp: 'ギリシャ', pattern: /\b(greece|greek|hellas)\b/i },
  { code: 'GRD', name: 'Grenada', nameJp: 'グレナダ', pattern: /\b(grenad[a]?(?:ian)?)\b/i },
  { code: 'GLP', name: 'Guadeloupe', nameJp: 'グアドループ', pattern: /\b(guadeloupe(?:an)?)\b/i },
  { code: 'GUM', name: 'Guam', nameJp: 'グアム', pattern: /\b(guam(?:anian)?)\b/i },
  { code: 'GTM', name: 'Guatemala', nameJp: 'グアテマラ', pattern: /\b(guatemala[n]?)\b/i },
  { code: 'GIN', name: 'Guinea', nameJp: 'ギニア', pattern: /\b(guinea(?:n)?)\b/i },
  {
    code: 'GNB',
    name: 'Guinea-Bissau',
    nameJp: 'ギニアビサウ',
    pattern: /\b(guinea[- ]bissau)\b/i,
  },
  { code: 'GUY', name: 'Guyana', nameJp: 'ガイアナ', pattern: /\b(guyan[a]?(?:ese)?)\b/i },
  { code: 'HTI', name: 'Haiti', nameJp: 'ハイチ', pattern: /\b(haiti(?:an)?)\b/i },
  { code: 'HND', name: 'Honduras', nameJp: 'ホンジュラス', pattern: /\b(honduras|honduran)\b/i },
  { code: 'HKG', name: 'Hong Kong', nameJp: '香港', pattern: /\b(hong\s+kong(?:er)?)\b/i },
  { code: 'HUN', name: 'Hungary', nameJp: 'ハンガリー', pattern: /\b(hungar[y]?(?:ian)?)\b/i },
  { code: 'ISL', name: 'Iceland', nameJp: 'アイスランド', pattern: /\b(icelan[d]?(?:ic|er)?)\b/i },
  { code: 'IND', name: 'India', nameJp: 'インド', pattern: /\b(indi[a]?(?:an)?|hindustan)\b/i },
  { code: 'IDN', name: 'Indonesia', nameJp: 'インドネシア', pattern: /\b(indonesi[a]?(?:an)?)\b/i },
  { code: 'IRN', name: 'Iran', nameJp: 'イラン', pattern: /\b(ira[n]?(?:ian)?|persia[n]?)\b/i },
  { code: 'IRQ', name: 'Iraq', nameJp: 'イラク', pattern: /\b(ira[q](?:i)?)\b/i },
  { code: 'IRE', name: 'Ireland', nameJp: 'アイルランド', pattern: /\b(irelan[d]?|irish|éire)\b/i },
  { code: 'ISR', name: 'Israel', nameJp: 'イスラエル', pattern: /\b(isra(?:el|eli))\b/i },
  { code: 'ITA', name: 'Italy', nameJp: 'イタリア', pattern: /\b(ital[y]?(?:ian)?)\b/i },
  { code: 'JAM', name: 'Jamaica', nameJp: 'ジャマイカ', pattern: /\b(jamaica[n]?)\b/i },
  { code: 'JPN', name: 'Japan', nameJp: '日本', pattern: /\b(japa[n]?(?:ese)?|nippon)\b/i },
  { code: 'JOR', name: 'Jordan', nameJp: 'ヨルダン', pattern: /\b(jorda[n]?(?:ian)?)\b/i },
  {
    code: 'KAZ',
    name: 'Kazakhstan',
    nameJp: 'カザフスタン',
    pattern: /\b(kazakhsta[n]?(?:i)?)\b/i,
  },
  { code: 'KEN', name: 'Kenya', nameJp: 'ケニア', pattern: /\b(keny[a]?(?:an)?)\b/i },
  { code: 'KIR', name: 'Kiribati', nameJp: 'キリバス', pattern: /\b(kiribati)\b/i },
  { code: 'XKX', name: 'Kosovo', nameJp: 'コソボ', pattern: /\b(kosovo|kosovar)\b/i },
  { code: 'KWT', name: 'Kuwait', nameJp: 'クウェート', pattern: /\b(kuwait(?:i)?)\b/i },
  {
    code: 'KGZ',
    name: 'Kyrgyzstan',
    nameJp: 'キルギス',
    pattern: /\b(kyrgyzsta[n]?(?:i)?|kirghiz)\b/i,
  },
  { code: 'LAO', name: 'Laos', nameJp: 'ラオス', pattern: /\b(laos?(?:tian)?)\b/i },
  { code: 'LVA', name: 'Latvia', nameJp: 'ラトビア', pattern: /\b(latvia[n]?)\b/i },
  { code: 'LBN', name: 'Lebanon', nameJp: 'レバノン', pattern: /\b(leban(?:on|ese))\b/i },
  { code: 'LSO', name: 'Lesotho', nameJp: 'レソト', pattern: /\b(lesotho)\b/i },
  { code: 'LBR', name: 'Liberia', nameJp: 'リベリア', pattern: /\b(liberi[a]?(?:an)?)\b/i },
  { code: 'LBY', name: 'Libya', nameJp: 'リビア', pattern: /\b(liby[a]?(?:an)?)\b/i },
  { code: 'LTU', name: 'Lithuania', nameJp: 'リトアニア', pattern: /\b(lithuania[n]?)\b/i },
  {
    code: 'LUX',
    name: 'Luxembourg',
    nameJp: 'ルクセンブルク',
    pattern: /\b(luxembourg(?:er)?)\b/i,
  },
  { code: 'MAC', name: 'Macau', nameJp: 'マカオ', pattern: /\b(maca[ou](?:nese)?)\b/i },
  {
    code: 'MDG',
    name: 'Madagascar',
    nameJp: 'マダガスカル',
    pattern: /\b(madagascar|malagasy)\b/i,
  },
  { code: 'MWI', name: 'Malawi', nameJp: 'マラウイ', pattern: /\b(malaw[i]?(?:an)?)\b/i },
  { code: 'MYS', name: 'Malaysia', nameJp: 'マレーシア', pattern: /\b(malaysia[n]?)\b/i },
  { code: 'MDV', name: 'Maldives', nameJp: 'モルディブ', pattern: /\b(maldiv(?:es|ian))\b/i },
  { code: 'MLI', name: 'Mali', nameJp: 'マリ', pattern: /\b(mali(?:an)?)\b/i },
  { code: 'MLT', name: 'Malta', nameJp: 'マルタ', pattern: /\b(malt[a]?(?:ese)?)\b/i },
  {
    code: 'MHL',
    name: 'Marshall Islands',
    nameJp: 'マーシャル諸島',
    pattern: /\b(marshall\s+islands|marshallese)\b/i,
  },
  {
    code: 'MTQ',
    name: 'Martinique',
    nameJp: 'マルティニーク',
    pattern: /\b(martiniq(?:ue|uais))\b/i,
  },
  {
    code: 'MRT',
    name: 'Mauritania',
    nameJp: 'モーリタニア',
    pattern: /\b(mauritani[a]?(?:an)?)\b/i,
  },
  { code: 'MUS', name: 'Mauritius', nameJp: 'モーリシャス', pattern: /\b(mauritiu[s]?(?:an)?)\b/i },
  { code: 'MEX', name: 'Mexico', nameJp: 'メキシコ', pattern: /\b(mexico|mexican|méx(?:ico)?)\b/i },
  {
    code: 'FSM',
    name: 'Micronesia',
    nameJp: 'ミクロネシア連邦',
    pattern: /\b(micronesi[a]?(?:an)?)\b/i,
  },
  { code: 'MDA', name: 'Moldova', nameJp: 'モルドバ', pattern: /\b(moldov[a]?(?:an)?)\b/i },
  { code: 'MNG', name: 'Mongolia', nameJp: 'モンゴル', pattern: /\b(mongoli[a]?(?:an)?)\b/i },
  { code: 'MNE', name: 'Montenegro', nameJp: 'モンテネグロ', pattern: /\b(montenegr(?:o|in))\b/i },
  { code: 'MAR', name: 'Morocco', nameJp: 'モロッコ', pattern: /\b(morocc(?:o|an))\b/i },
  {
    code: 'MOZ',
    name: 'Mozambique',
    nameJp: 'モザンビーク',
    pattern: /\b(mozambiqu[e]?(?:an)?)\b/i,
  },
  { code: 'MMR', name: 'Myanmar', nameJp: 'ミャンマー', pattern: /\b(myanmar|burma(?:ese)?)\b/i },
  { code: 'NAM', name: 'Namibia', nameJp: 'ナミビア', pattern: /\b(namibi[a]?(?:an)?)\b/i },
  { code: 'NRU', name: 'Nauru', nameJp: 'ナウル', pattern: /\b(nauru(?:an)?)\b/i },
  { code: 'NPL', name: 'Nepal', nameJp: 'ネパール', pattern: /\b(nepa[l]?(?:ese|i)?)\b/i },
  {
    code: 'NLD',
    name: 'Netherlands',
    nameJp: 'オランダ',
    pattern: /\b(netherlands|dutch|holland)\b/i,
  },
  {
    code: 'NCL',
    name: 'New Caledonia',
    nameJp: 'ニューカレドニア',
    pattern: /\b(new\s+caledoni[a]?(?:an)?)\b/i,
  },
  {
    code: 'NZL',
    name: 'New Zealand',
    nameJp: 'ニュージーランド',
    pattern: /\b(new\s+zealand|kiwi[s]?|nz)\b/i,
  },
  { code: 'NIC', name: 'Nicaragua', nameJp: 'ニカラグア', pattern: /\b(nicaragua[n]?)\b/i },
  { code: 'NER', name: 'Niger', nameJp: 'ニジェール', pattern: /\b(niger(?:ien)?)\b/i },
  { code: 'NGA', name: 'Nigeria', nameJp: 'ナイジェリア', pattern: /\b(nigeri[a]?(?:an)?)\b/i },
  { code: 'PRK', name: 'North Korea', nameJp: '北朝鮮', pattern: /\b(north\s+korea[n]?)\b/i },
  {
    code: 'MKD',
    name: 'North Macedonia',
    nameJp: '北マケドニア',
    pattern: /\b(north\s+macedonia[n]?|macedonia[n]?)\b/i,
  },
  { code: 'NOR', name: 'Norway', nameJp: 'ノルウェー', pattern: /\b(norwa[y]?(?:egian)?)\b/i },
  { code: 'OMN', name: 'Oman', nameJp: 'オマーン', pattern: /\b(oma[n]?(?:i)?)\b/i },
  { code: 'PAK', name: 'Pakistan', nameJp: 'パキスタン', pattern: /\b(pakista[n]?(?:i)?)\b/i },
  { code: 'PLW', name: 'Palau', nameJp: 'パラオ', pattern: /\b(palau(?:an)?)\b/i },
  { code: 'PSE', name: 'Palestine', nameJp: 'パレスチナ', pattern: /\b(palestin(?:e|ian))\b/i },
  { code: 'PAN', name: 'Panama', nameJp: 'パナマ', pattern: /\b(panama(?:nian)?)\b/i },
  {
    code: 'PNG',
    name: 'Papua New Guinea',
    nameJp: 'パプアニューギニア',
    pattern: /\b(papua\s+new\s+guinea)\b/i,
  },
  { code: 'PRY', name: 'Paraguay', nameJp: 'パラグアイ', pattern: /\b(paraguay(?:an)?)\b/i },
  { code: 'PER', name: 'Peru', nameJp: 'ペルー', pattern: /\b(per[uú](?:vian)?)\b/i },
  {
    code: 'PHL',
    name: 'Philippines',
    nameJp: 'フィリピン',
    pattern: /\b(philippine[s]?|filipino|pilipino)\b/i,
  },
  { code: 'POL', name: 'Poland', nameJp: 'ポーランド', pattern: /\b(polan[d]?|polish)\b/i },
  { code: 'PRT', name: 'Portugal', nameJp: 'ポルトガル', pattern: /\b(portug(?:al|uese))\b/i },
  {
    code: 'PRI',
    name: 'Puerto Rico',
    nameJp: 'プエルトリコ',
    pattern: /\b(puerto\s+ric(?:o|an))\b/i,
  },
  { code: 'QAT', name: 'Qatar', nameJp: 'カタール', pattern: /\b(qatar(?:i)?)\b/i },
  {
    code: 'COG',
    name: 'Republic of the Congo',
    nameJp: 'コンゴ共和国',
    pattern: /\b(republic\s+of\s+(?:the\s+)?congo|congo(?!\s*,\s*dr))\b/i,
  },
  { code: 'REU', name: 'Réunion', nameJp: 'レユニオン', pattern: /\b(r[eé]union(?:nais)?)\b/i },
  { code: 'ROU', name: 'Romania', nameJp: 'ルーマニア', pattern: /\b(romani[a]?(?:an)?)\b/i },
  { code: 'RUS', name: 'Russia', nameJp: 'ロシア', pattern: /\b(russia[n]?|россия)\b/i },
  { code: 'RWA', name: 'Rwanda', nameJp: 'ルワンダ', pattern: /\b(rwand[a]?(?:an)?)\b/i },
  {
    code: 'KNA',
    name: 'Saint Kitts and Nevis',
    nameJp: 'セントクリストファー・ネイビス',
    pattern: /\b(saint\s+kitts(?:\s+and\s+nevis)?|st\.?\s+kitts)\b/i,
  },
  {
    code: 'LCA',
    name: 'Saint Lucia',
    nameJp: 'セントルシア',
    pattern: /\b(saint\s+lucia[n]?|st\.?\s+lucia)\b/i,
  },
  {
    code: 'VCT',
    name: 'Saint Vincent and the Grenadines',
    nameJp: 'セントビンセント・グレナディーン',
    pattern: /\b(saint\s+vincent|st\.?\s+vincent)\b/i,
  },
  { code: 'WSM', name: 'Samoa', nameJp: 'サモア', pattern: /\b(samo[a]?(?:n)?)\b/i },
  {
    code: 'STP',
    name: 'São Tomé and Príncipe',
    nameJp: 'サントメ・プリンシペ',
    pattern: /\b(s[aã]o\s+tom[eé](?:\s+and\s+pr[ií]ncipe)?)\b/i,
  },
  {
    code: 'SAU',
    name: 'Saudi Arabia',
    nameJp: 'サウジアラビア',
    pattern: /\b(saudi\s+arabia[n]?|ksa)\b/i,
  },
  { code: 'SEN', name: 'Senegal', nameJp: 'セネガル', pattern: /\b(senega[l]?(?:ese)?)\b/i },
  { code: 'SRB', name: 'Serbia', nameJp: 'セルビア', pattern: /\b(serbia[n]?)\b/i },
  { code: 'SYC', name: 'Seychelles', nameJp: 'セーシェル', pattern: /\b(seychell(?:es|ois))\b/i },
  {
    code: 'SLE',
    name: 'Sierra Leone',
    nameJp: 'シエラレオネ',
    pattern: /\b(sierra\s+leone(?:an)?)\b/i,
  },
  { code: 'SGP', name: 'Singapore', nameJp: 'シンガポール', pattern: /\b(singapore(?:an)?)\b/i },
  { code: 'SVK', name: 'Slovakia', nameJp: 'スロバキア', pattern: /\b(slovakia[n]?)\b/i },
  { code: 'SVN', name: 'Slovenia', nameJp: 'スロベニア', pattern: /\b(slovenia[n]?)\b/i },
  {
    code: 'SLB',
    name: 'Solomon Islands',
    nameJp: 'ソロモン諸島',
    pattern: /\b(solomon\s+islands)\b/i,
  },
  { code: 'SOM', name: 'Somalia', nameJp: 'ソマリア', pattern: /\b(somali[a]?(?:an)?)\b/i },
  {
    code: 'ZAF',
    name: 'South Africa',
    nameJp: '南アフリカ',
    pattern: /\b(south\s+africa[n]?|s\.a\.|rsa)\b/i,
  },
  {
    code: 'KOR',
    name: 'South Korea',
    nameJp: '韓国',
    pattern: /\b(south\s+korea[n]?|republic\s+of\s+korea)\b/i,
  },
  {
    code: 'SSD',
    name: 'South Sudan',
    nameJp: '南スーダン',
    pattern: /\b(south\s+suda[n]?(?:ese)?)\b/i,
  },
  { code: 'ESP', name: 'Spain', nameJp: 'スペイン', pattern: /\b(spain|spanish|españa)\b/i },
  {
    code: 'LKA',
    name: 'Sri Lanka',
    nameJp: 'スリランカ',
    pattern: /\b(sri\s+lanka[n]?|ceylon)\b/i,
  },
  { code: 'SDN', name: 'Sudan', nameJp: 'スーダン', pattern: /\b(suda[n]?(?:ese)?)\b/i },
  { code: 'SUR', name: 'Suriname', nameJp: 'スリナム', pattern: /\b(surinam[e]?(?:se)?)\b/i },
  { code: 'SWE', name: 'Sweden', nameJp: 'スウェーデン', pattern: /\b(swed(?:en|ish|e))\b/i },
  {
    code: 'CHE',
    name: 'Switzerland',
    nameJp: 'スイス',
    pattern: /\b(switzerland|swiss|schweiz|suisse)\b/i,
  },
  { code: 'SYR', name: 'Syria', nameJp: 'シリア', pattern: /\b(syr(?:ia|ian))\b/i },
  { code: 'TWN', name: 'Taiwan', nameJp: '台湾', pattern: /\b(taiwan(?:ese)?|r\.o\.c\.?)\b/i },
  {
    code: 'TJK',
    name: 'Tajikistan',
    nameJp: 'タジキスタン',
    pattern: /\b(tajikista[n]?(?:i)?)\b/i,
  },
  { code: 'TZA', name: 'Tanzania', nameJp: 'タンザニア', pattern: /\b(tanzani[a]?(?:an)?)\b/i },
  { code: 'THA', name: 'Thailand', nameJp: 'タイ', pattern: /\b(thailand|thai)\b/i },
  {
    code: 'TLS',
    name: 'Timor-Leste',
    nameJp: '東ティモール',
    pattern: /\b(timor[- ]leste|east\s+timor(?:ese)?)\b/i,
  },
  { code: 'TGO', name: 'Togo', nameJp: 'トーゴ', pattern: /\b(togo(?:lese)?)\b/i },
  { code: 'TON', name: 'Tonga', nameJp: 'トンガ', pattern: /\b(tonga[n]?)\b/i },
  {
    code: 'TTO',
    name: 'Trinidad and Tobago',
    nameJp: 'トリニダード・トバゴ',
    pattern: /\b(trinidad\s+(?:and\s+)?tobago)\b/i,
  },
  { code: 'TUN', name: 'Tunisia', nameJp: 'チュニジア', pattern: /\b(tunisi[a]?(?:an)?)\b/i },
  { code: 'TUR', name: 'Turkey', nameJp: 'トルコ', pattern: /\b(turke[y]?(?:ish)?|türkiye)\b/i },
  {
    code: 'TKM',
    name: 'Turkmenistan',
    nameJp: 'トルクメニスタン',
    pattern: /\b(turkmenista[n]?(?:i)?)\b/i,
  },
  { code: 'TUV', name: 'Tuvalu', nameJp: 'ツバル', pattern: /\b(tuvalu(?:an)?)\b/i },
  { code: 'UGA', name: 'Uganda', nameJp: 'ウガンダ', pattern: /\b(ugand[a]?(?:an)?)\b/i },
  { code: 'UKR', name: 'Ukraine', nameJp: 'ウクライナ', pattern: /\b(ukrain[e]?(?:ian)?)\b/i },
  {
    code: 'UAE',
    name: 'United Arab Emirates',
    nameJp: 'アラブ首長国連邦',
    pattern: /\b(united\s+arab\s+emirates|u\.a\.e\.?|emirates)\b/i,
  },
  {
    code: 'GBR',
    name: 'United Kingdom',
    nameJp: 'イギリス',
    pattern:
      /\b(united\s+kingdom|great\s+britain|england|scotland|wales|northern\s+ireland|britain|uk|u\.k\.)\b/i,
  },
  {
    code: 'USA',
    name: 'United States',
    nameJp: 'アメリカ',
    pattern:
      /\b(united\s+states(?:\s+of\s+america)?|u\.s\.a\.?|u\.s\.|usa|murica|america[n]?|states)\b/i,
  },
  { code: 'URY', name: 'Uruguay', nameJp: 'ウルグアイ', pattern: /\b(uruguay(?:an)?)\b/i },
  {
    code: 'UZB',
    name: 'Uzbekistan',
    nameJp: 'ウズベキスタン',
    pattern: /\b(uzbekista[n]?(?:i)?)\b/i,
  },
  { code: 'VUT', name: 'Vanuatu', nameJp: 'バヌアツ', pattern: /\b(vanuatu)\b/i },
  {
    code: 'VAT',
    name: 'Vatican City',
    nameJp: 'バチカン市国',
    pattern: /\b(vatican(?:\s+city)?|holy\s+see)\b/i,
  },
  { code: 'VEN', name: 'Venezuela', nameJp: 'ベネズエラ', pattern: /\b(venezuela[n]?)\b/i },
  { code: 'VNM', name: 'Vietnam', nameJp: 'ベトナム', pattern: /\b(vietna(?:m|mese))\b/i },
  { code: 'YEM', name: 'Yemen', nameJp: 'イエメン', pattern: /\b(yeme[n]?(?:i)?)\b/i },
  { code: 'ZMB', name: 'Zambia', nameJp: 'ザンビア', pattern: /\b(zambi[a]?(?:an)?)\b/i },
  { code: 'ZWE', name: 'Zimbabwe', nameJp: 'ジンバブエ', pattern: /\b(zimbabw[e]?(?:an)?)\b/i },
];

/**
 * Scans a donor comment for a country mention and returns the ISO 3166-1 alpha-3
 * country code, or null if no country (or more than one distinct country) is found.
 */
export function detectCountryFromComment(comment: string | null | undefined): string | null {
  if (!comment) {
    return null;
  }

  let firstCode: string | null = null;
  let firstIndex = Infinity;
  for (const { code, pattern } of COUNTRY_PATTERNS) {
    const match = pattern.exec(comment);
    if (match && match.index < firstIndex) {
      firstIndex = match.index;
      firstCode = code;
    }
  }
  return firstCode;
}

export function countryCodeToName(code: string, locale: string = 'EN'): string {
  const entry = COUNTRY_PATTERNS.find((c) => c.code === code);
  if (!entry) {
    return code;
  }
  return locale === 'JP' ? entry.nameJp : entry.name;
}
