import type { DataPattern } from './types';

export const GACHA_PATTERNS: DataPattern[] = [
  {
    name: 'Arknights: Endfield',
    nameJa: 'アークナイツ：エンドフィールド',
    id: 'arknights-endfield',
    pattern: /\b(arknights\s*endfield|endfield)\b/i,
  },
  {
    name: 'Azur Lane',
    nameJa: 'アズールレーン',
    id: 'azur-lane',
    pattern: /\b(azur\s*lane|azur\s*ln|al)\b/i,
  },
  {
    name: 'Cookie Run: Kingdom',
    nameJa: 'クッキーラン：キングダム',
    id: 'cookie-run-kingdom',
    pattern: /\b(cookie\s*run\s*kingdom|crk)\b/i,
  },
  {
    name: 'Diablo Immortal',
    nameJa: 'ディアブロ イモータル',
    id: 'diablo-immortal',
    pattern: /\b(diablo\s*immortal)\b/i,
  },
  {
    name: 'Dragon Ball Z: Dokkan Battle',
    nameJa: 'ドラゴンボールZ ドッカンバトル',
    id: 'dokkan-battle',
    pattern: /\b(dokkan\s*battle|dbz\s*dokkan|dokkan)\b/i,
  },
  {
    name: 'Epic Seven',
    nameJa: 'エピックセブン',
    id: 'epic-seven',
    pattern: /\b(epic\s*seven|e7)\b/i,
  },
  {
    name: 'Fate/Grand Order',
    nameJa: 'フェイト／グランドオーダー',
    id: 'fate-grand-order',
    pattern: /\b(fate\s*\/?\s*grand\s*order|fgo|fate\s*go)\b/i,
  },
  {
    name: 'Final Fantasy Record Keeper',
    nameJa: 'ファイナルファンタジー レコードキーパー',
    id: 'final-fantasy-record-keeper',
    pattern: /\b(final\s*fantasy\s*record\s*keeper|ffrk)\b/i,
  },
  {
    name: 'Genshin Impact',
    nameJa: '原神',
    id: 'genshin-impact',
    pattern: /\b(genshin\s*impact|genshin)\b/i,
  },
  {
    name: 'Girls’ Frontline',
    nameJa: 'ドールズフロントライン',
    id: 'girls-frontline',
    pattern: /\b(girls\s*frontline|gfl)\b/i,
  },
  {
    name: 'Goddess of Victory: Nikke',
    nameJa: '勝利の女神：NIKKE',
    id: 'nikke',
    pattern: /\b(nikke|goddess\s*of\s*victory\s*:?\s*nikke)\b/i,
  },
  {
    name: 'Hatsune Miku: Colorful Stage!',
    nameJa: 'プロジェクトセカイ カラフルステージ！',
    id: 'colorful-stage',
    pattern: /\b(colorful\s*stage|project\s*sekai|proseka|pjsekai)\b/i,
  },
  {
    name: 'Honkai Impact 3rd',
    nameJa: '崩壊3rd',
    id: 'honkai-impact-3rd',
    pattern: /\b(honkai\s*impact\s*3rd|hi3)\b/i,
  },
  {
    name: 'Honkai: Star Rail',
    nameJa: '崩壊：スターレイル',
    id: 'honkai-star-rail',
    pattern: /\b(honkai\s*star\s*rail|hsr)\b/i,
  },
  {
    name: 'Infinity Nikki',
    nameJa: 'インフィニティニキ',
    id: 'infinity-nikki',
    pattern: /\b(infinity\s*nikki)\b/i,
  },
  {
    name: 'Kantai Collection',
    nameJa: '艦隊これくしょん',
    id: 'kantai-collection',
    pattern: /\b(kantai\s*collection|kancolle)\b/i,
  },
  {
    name: 'Limbus Company',
    nameJa: 'リンバス・カンパニー',
    id: 'limbus-company',
    pattern: /\b(limbus\s*company|project\s*moon|limbus)\b/i,
  },
  {
    name: 'Love and Deepspace',
    nameJa: '恋と深空',
    id: 'love-and-deepspace',
    pattern: /\b(love\s*and\s*deepspace|lad|deepspace)\b/i,
  },
  {
    name: 'Mahjong Soul',
    nameJa: '雀魂',
    id: 'mahjong-soul',
    pattern: /\b(mahjong\s*soul|majsoul)\b/i,
  },
  {
    name: 'NU: Carnival',
    nameJa: 'NU: カーニバル',
    id: 'nu-carnival',
    pattern: /\b(nu\s*:?carnival|nu\s*carnival)\b/i,
  },
  {
    name: 'Princess Connect! Re:Dive',
    nameJa: 'プリンセスコネクト！Re:Dive',
    id: 'princess-connect-re-dive',
    pattern: /\b(princess\s*connect|priconne|re\s*:?dive)\b/i,
  },
  {
    name: 'Pokémon Masters EX',
    nameJa: 'ポケモンマスターズEX',
    id: 'pokemon-masters-ex',
    pattern: /\b(pokemon\s*masters\s*ex|poma|pmex)\b/i,
  },
  {
    name: 'Raid: Shadow Legends',
    nameJa: 'レイド:シャドウレジェンド',
    id: 'raid-shadow-legends',
    pattern: /\b(raid\s*shadow\s*legends)\b/i,
  },
  {
    name: 'SD Gundam G Generation Eternal',
    nameJa: 'SDガンダム ジージェネレーション エターナル',
    id: 'sd-gundam-g-generation-eternal',
    pattern: /\b(sd\s*gundam\s*g\s*generation\s*eternal|g\s*generation\s*eternal|ggen|g-gen)\b/i,
  },
  {
    name: 'The Battle Cats',
    nameJa: 'にゃんこ大戦争',
    id: 'the-battle-cats',
    pattern: /\b(battle\s*cats|the\s*battle\s*cats|nyanko)\b/i,
  },
  {
    name: 'The Idolmaster: Gakuen Idolmaster',
    nameJa: '学園アイドルマスター',
    id: 'gakuen-idolmaster',
    pattern: /\b(gakuen\s*idolmaster|idolmaster\s*gakuen|gakumas)\b/i,
  },
  {
    name: 'Tower of Fantasy',
    nameJa: '幻塔',
    id: 'tower-of-fantasy',
    pattern: /\b(tower\s*of\s*fantasy|tof)\b/i,
  },
  {
    name: 'Uma Musume: Pretty Derby',
    nameJa: 'ウマ娘 プリティーダービー',
    id: 'uma-musume-pretty-derby',
    pattern: /\b(uma\s*musume|umamusume|pretty\s*derby|umapyoi)\b/i,
  },
  {
    name: 'Wuthering Waves',
    nameJa: '鳴潮',
    id: 'wuthering-waves',
    pattern: /\b(wuthering\s*waves|wuwa)\b/i,
  },
  {
    name: 'Zenless Zone Zero',
    nameJa: 'ゼンレスゾーンゼロ',
    id: 'zenless-zone-zero',
    pattern: /\b(zenless\s*zone\s*zero|zzz)\b/i,
  },
];
