import type { DataPattern } from './types';

export const GAME_PATTERNS: DataPattern[] = [
  {
    name: 'Alien: Isolation',
    nameJa: 'エイリアン アイソレーション',
    id: 'alien-isolation',
    pattern: /\b(alien\s*isolation)\b/i,
  },
  {
    name: 'Amnesia: The Dark Descent',
    nameJa: 'アムネシア：ダークディセント',
    id: 'amnesia-dark-descent',
    pattern: /\b(amnesia\s*the\s*dark\s*descent|amnesia)\b/i,
  },
  {
    name: 'Armored Core',
    nameJa: 'アーマード・コア',
    id: 'armored-core',
    pattern: /\b(armored\s*core)\b/i,
  },
  {
    name: 'Command & Conquer: Red Alert',
    nameJa: 'コマンド＆コンカー レッドアラート',
    id: 'red-alert',
    pattern: /\b(red\s*alert|command\s*(and|&)\s*conquer)\b/i,
  },
  {
    name: 'Connect Four',
    nameJa: 'コネクトフォー',
    id: 'connect-four',
    pattern: /\b(connect\s*four)\b/i,
  },
  {
    name: 'Crow Country',
    nameJa: 'クロウカントリー',
    id: 'crow-country',
    pattern: /\b(crow\s*country)\b/i,
  },
  {
    name: 'Cyberpunk 2077',
    nameJa: 'サイバーパンク2077',
    id: 'cyberpunk-2077',
    pattern: /\b(cyberpunk\s*2077|cp2077)\b/i,
  },
  {
    name: 'Dark Souls III',
    nameJa: 'ダークソウルIII',
    id: 'dark-souls-3',
    pattern: /\b(dark\s*souls\s*3|ds3)\b/i,
  },
  { name: 'Deltarune', nameJa: 'デルタルーン', id: 'deltarune', pattern: /\b(deltarune)\b/i },
  { name: 'Dredge', nameJa: 'ドレッジ', id: 'dredge', pattern: /\b(dredge)\b/i },
  {
    name: 'Dwarf Fortress',
    nameJa: 'ドワーフフォートレス',
    id: 'dwarf-fortress',
    pattern: /\b(dwarf\s*fortress|df)\b/i,
  },
  {
    name: 'Factorio',
    nameJa: 'ファクトリオ',
    id: 'factorio',
    pattern: /\b(factorio|space\s*age)\b/i,
  },
  {
    name: 'Fallout: New Vegas',
    nameJa: 'フォールアウト：ニューベガス',
    id: 'fallout-new-vegas',
    pattern: /\b(new\s*vegas|fallout\s*new\s*vegas)\b/i,
  },
  {
    name: 'F.E.A.R.',
    nameJa: 'フィアー',
    id: 'fear',
    pattern: /\b(f\.?e\.?a\.?r\.?|first\s*encounter\s*assault\s*recon)\b/i,
  },
  {
    name: 'Final Fantasy XIV',
    nameJa: 'ファイナルファンタジーXIV',
    id: 'final-fantasy-xiv',
    pattern: /\b(ffxiv|ff14|final\s*fantasy\s*(xiv|14))\b/i,
  },
  {
    name: 'Hello Kitty Island Adventure',
    nameJa: 'ハローキティ アイランドアドベンチャー',
    id: 'hello-kitty-island-adventure',
    pattern: /\b(hkia|hello\s*kitty\s*island\s*adventure)\b/i,
  },
  {
    name: 'Hollow Knight',
    nameJa: 'ホロウナイト',
    id: 'hollow-knight',
    pattern: /\b(hollow\s*knight)\b/i,
  },
  {
    name: 'Jak and Daxter',
    nameJa: 'ジャック×ダクスター',
    id: 'jak-and-daxter',
    pattern: /\b(jak\s*and\s*daxter)\b/i,
  },
  {
    name: 'Legacy of Kain: Soul Reaver',
    nameJa: 'レガシー・オブ・ケイン：ソウルリーバー',
    id: 'soul-reaver',
    pattern: /\b(soul\s*reaver|legacy\s*of\s*kain)\b/i,
  },
  {
    name: 'Limbus Company',
    nameJa: 'リンバス・カンパニー',
    id: 'limbus-company',
    pattern: /\b(limbus\s*company|limbus)\b/i,
  },
  {
    name: 'Love and Deepspace',
    nameJa: '恋と深空',
    id: 'love-and-deepspace',
    pattern: /\b(love\s*and\s*deepspace|lad)\b/i,
  },
  {
    name: 'Mass Effect',
    nameJa: 'マスエフェクト',
    id: 'mass-effect',
    pattern: /\b(mass\s*effect)\b/i,
  },
  {
    name: 'Monkey Island',
    nameJa: 'モンキーアイランド',
    id: 'monkey-island',
    pattern: /\b(monkey\s*island)\b/i,
  },
  { name: 'NEKOPARA', nameJa: 'ネコぱら', id: 'nekopara', pattern: /\b(nekopara)\b/i },
  {
    name: 'NieR: Automata',
    nameJa: 'ニーア オートマタ',
    id: 'nier-automata',
    pattern: /\b(nier\s*automata|nier)\b/i,
  },
  { name: 'Noita', nameJa: 'ノイタ', id: 'noita', pattern: /\b(noita)\b/i },
  { name: 'OMORI', nameJa: 'オモリ', id: 'omori', pattern: /\b(omori)\b/i },
  {
    name: 'Outer Wilds',
    nameJa: 'アウターワイルズ',
    id: 'outer-wilds',
    pattern: /\b(outer\s*wilds)\b/i,
  },
  { name: 'Persona 3', nameJa: 'ペルソナ3', id: 'persona-3', pattern: /\b(persona\s*3|p3)\b/i },
  {
    name: 'Pokémon Mystery Dungeon: Explorers of Sky',
    nameJa: 'ポケモン不思議のダンジョン 空の探検隊',
    id: 'pmd-explorers-of-sky',
    pattern: /\b(explorers\s*of\s*sky|pokemon\s*mystery\s*dungeon)\b/i,
  },
  {
    name: 'Ridge Racer Type 4',
    nameJa: 'リッジレーサータイプ4',
    id: 'ridge-racer-type-4',
    pattern: /\b(ridge\s*racer\s*type\s*4|rr4)\b/i,
  },
  { name: 'RimWorld', nameJa: 'リムワールド', id: 'rimworld', pattern: /\b(rimworld)\b/i },
  {
    name: 'Sekiro: Shadows Die Twice',
    nameJa: '隻狼',
    id: 'sekiro',
    pattern: /\b(sekiro|shadows\s*die\s*twice)\b/i,
  },
  { name: 'SIGNALIS', nameJa: 'シグナリス', id: 'signalis', pattern: /\b(signalis)\b/i },
  {
    name: 'Silent Hill 2',
    nameJa: 'サイレントヒル2',
    id: 'silent-hill-2',
    pattern: /\b(silent\s*hill\s*2)\b/i,
  },
  {
    name: 'Slay the Spire 2',
    nameJa: 'スレイザスパイア2',
    id: 'slay-the-spire-2',
    pattern: /\b(slay\s*the\s*spire\s*2|sts2)\b/i,
  },
  {
    name: 'Sonic Riders',
    nameJa: 'ソニックライダーズ',
    id: 'sonic-riders',
    pattern: /\b(sonic\s*riders)\b/i,
  },
  {
    name: 'SpongeBob SquarePants: The Movie Game',
    nameJa: 'スポンジ・ボブ ザ・ムービー',
    id: 'spongebob-movie-game',
    pattern: /\b(spongebob.*movie\s*game)\b/i,
  },
  {
    name: 'S.T.A.L.K.E.R.: Shadow of Chernobyl',
    nameJa: 'ストーカー：チェルノブイリの影',
    id: 'stalker-shadow-of-chernobyl',
    pattern: /\b(stalker|s\.?t\.?a\.?l\.?k\.?e\.?r|shadow\s*of\s*ch(e|o)rnobyl)\b/i,
  },
  {
    name: 'Stardew Valley',
    nameJa: 'スターデューバレー',
    id: 'stardew-valley',
    pattern: /\b(stardew\s*valley)\b/i,
  },
  { name: 'Terraria', nameJa: 'テラリア', id: 'terraria', pattern: /\b(terraria|calamity)\b/i },
  {
    name: 'The Battle Cats',
    nameJa: 'にゃんこ大戦争',
    id: 'battle-cats',
    pattern: /\b(battle\s*cats|nyanko)\b/i,
  },
  {
    name: 'The Lost Legends of Redwall: The Scout',
    nameJa: 'レッドウォールの失われた伝説：スカウト',
    id: 'redwall-the-scout',
    pattern: /\b(redwall)\b/i,
  },
  { name: 'TUNIC', nameJa: 'チュニック', id: 'tunic', pattern: /\b(tunic)\b/i },
  {
    name: 'What Remains of Edith Finch',
    nameJa: 'エディス・フィンチの記憶',
    id: 'edith-finch',
    pattern: /\b(edith\s*finch)\b/i,
  },
];
