import type { DataPattern } from './types';

export const IRONMOUSE_PATTERNS: DataPattern[] = [
  {
    id: 'birthday-model-2026',
    name: 'Birthday Model 2026',
    nameJa: '2026年バースデーモデル',
    url: 'https://www.ironmousemodelindex.com/model0052',
    pattern: /birthday\s*model\s*2026/i,
  },
  {
    id: 'angel-of-music',
    name: 'Angel of Music',
    nameJa: '音楽の天使',
    url: 'https://www.ironmousemodelindex.com/model0051',
    pattern: /angel\s*of\s*music/i,
  },
  {
    id: 'mouseyquinn',
    name: 'MouseyQuinn',
    nameJa: 'マウジークイン',
    url: 'https://www.ironmousemodelindex.com/model0050',
    pattern: /mousey\s*quinn/i,
  },
  {
    id: '8th-anniversary',
    name: '8th Anniversary',
    nameJa: '8周年',
    url: 'https://www.ironmousemodelindex.com/model0049',
    pattern: /8(th)?\s*anniversary/i,
  },
  {
    id: 'mouse-of-the-cloth',
    name: 'Mouse of the Cloth',
    nameJa: 'クロスのマウス',
    url: 'https://www.ironmousemodelindex.com/model0048',
    pattern: /mouse\s*of\s*the\s*cloth/i,
  },
  {
    id: 'rise-mouse',
    name: 'Rise Mouse',
    nameJa: 'ライズマウス',
    url: 'https://www.ironmousemodelindex.com/model0047',
    pattern: /rise\s*mouse/i,
  },
  {
    id: 'iron-rose',
    name: 'Iron Rose',
    nameJa: 'アイアンローズ',
    url: 'https://www.ironmousemodelindex.com/model0046',
    pattern: /iron\s*rose/i,
  },
  {
    id: 'miku-mouse',
    name: 'Miku Mouse',
    nameJa: 'ミクマウス',
    url: 'https://www.ironmousemodelindex.com/model0045',
    pattern: /miku\s*mouse/i,
  },
  {
    id: 'cyber-mouse',
    name: 'Cyber Mouse',
    nameJa: 'サイバーマウス',
    url: 'https://www.ironmousemodelindex.com/model0044',
    pattern: /cyber\s*mouse/i,
  },
  {
    id: 'dark-bloom',
    name: 'Dark Bloom',
    nameJa: 'ダークブルーム',
    url: 'https://www.ironmousemodelindex.com/model0043',
    pattern: /dark\s*bloom/i,
  },
  {
    id: 'season-3-3d',
    name: 'Season 3 3D',
    nameJa: 'シーズン3 3D',
    url: 'https://www.ironmousemodelindex.com/model0042',
    pattern: /season\s*3\s*3d/i,
  },
  {
    id: 'moonlight-demon',
    name: 'Moonlight Demon',
    nameJa: 'ムーンライトデーモン',
    url: 'https://www.ironmousemodelindex.com/model0041',
    pattern: /moonlight\s*demon/i,
  },
  {
    id: 'bloom-angel-3d',
    name: 'Bloom Angel 3D',
    nameJa: 'ブルームエンジェル3D',
    url: 'https://www.ironmousemodelindex.com/model0040',
    pattern: /bloom\s*angel\s*3d/i,
  },
  {
    id: 'infernal-cult-princess-3d',
    name: 'Infernal Cult Princess 3D',
    nameJa: '地獄カルトプリンセス3D',
    url: 'https://www.ironmousemodelindex.com/model0039',
    pattern: /infernal\s*cult\s*princess\s*3d/i,
  },
  {
    id: 'witch-of-twitch',
    name: 'Witch of Twitch',
    nameJa: 'ツイッチの魔女',
    url: 'https://www.ironmousemodelindex.com/model0038',
    pattern: /witch\s*of\s*twitch/i,
  },
  {
    id: 'ultimate-delinquent-2d',
    name: 'Ultimate Delinquent 2D',
    nameJa: '不良2D',
    url: 'https://www.ironmousemodelindex.com/model0037',
    pattern: /ultimate\s*delinquent\s*2d/i,
  },
  {
    id: 'infernal-cult-princess',
    name: 'Infernal Cult Princess',
    nameJa: '地獄カルトプリンセス',
    url: 'https://www.ironmousemodelindex.com/model0036',
    pattern: /infernal\s*cult\s*princess(?!\s*3d)/i,
  },
  {
    id: 'decora',
    name: 'Decora',
    nameJa: 'デコラ',
    url: 'https://www.ironmousemodelindex.com/model0035',
    pattern: /decora/i,
  },
  {
    id: 'pudding',
    name: 'Pudding',
    nameJa: 'プリン',
    url: 'https://www.ironmousemodelindex.com/model0034',
    pattern: /pudding/i,
  },
  {
    id: 'ultimate-delinquent',
    name: 'Ultimate Delinquent',
    nameJa: '不良',
    url: 'https://www.ironmousemodelindex.com/model0033',
    pattern: /ultimate\s*delinquent(?!\s*2d)/i,
  },
  {
    id: 'rainbow-idol',
    name: 'Rainbow Idol',
    nameJa: 'レインボーアイドル',
    url: 'https://www.ironmousemodelindex.com/model0032',
    pattern: /rainbow\s*idol/i,
  },
  {
    id: 'cotton-candy-3d',
    name: 'Cotton Candy 3D',
    nameJa: 'コットンキャンディ3D',
    url: 'https://www.ironmousemodelindex.com/model0031',
    pattern: /cotton\s*candy\s*3d/i,
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    nameJa: 'コットンキャンディ',
    url: 'https://www.ironmousemodelindex.com/model0030',
    pattern: /cotton\s*candy(?!\s*3d)/i,
  },
  {
    id: 'sweet-nightmares',
    name: 'Sweet Nightmares',
    nameJa: 'スイートナイトメア',
    url: 'https://www.ironmousemodelindex.com/model0029',
    pattern: /sweet\s*nightmares/i,
  },
  {
    id: 'winter-doll',
    name: 'Winter Doll',
    nameJa: 'ウィンタードール',
    url: 'https://www.ironmousemodelindex.com/model0028',
    pattern: /winter\s*doll/i,
  },
  {
    id: 'candy-pop',
    name: 'Candy Pop',
    nameJa: 'キャンディポップ',
    url: 'https://www.ironmousemodelindex.com/model0027',
    pattern: /candy\s*pop/i,
  },
  {
    id: 'yokai-hunter',
    name: 'Yokai Hunter',
    nameJa: '妖怪ハンター',
    url: 'https://www.ironmousemodelindex.com/model0026',
    pattern: /yokai\s*hunter/i,
  },
  {
    id: 'season-3',
    name: 'Season 3',
    nameJa: 'シーズン3',
    url: 'https://www.ironmousemodelindex.com/model0025',
    pattern: /season\s*3(?!\s*3d)/i,
  },
  {
    id: 'brat-princess',
    name: 'Brat Princess',
    nameJa: 'ブラットプリンセス',
    url: 'https://www.ironmousemodelindex.com/model0024',
    pattern: /brat\s*princess/i,
  },
  {
    id: 'bloom-angel',
    name: 'Bloom Angel',
    nameJa: 'ブルームエンジェル',
    url: 'https://www.ironmousemodelindex.com/model0023',
    pattern: /bloom\s*angel(?!\s*3d)/i,
  },
  {
    id: 'trickster',
    name: 'Trickster',
    nameJa: 'トリックスター',
    url: 'https://www.ironmousemodelindex.com/model0022',
    pattern: /trickster/i,
  },
  {
    id: 'racing-princess',
    name: 'Racing Princess',
    nameJa: 'レーシングプリンセス',
    url: 'https://www.ironmousemodelindex.com/model0021',
    pattern: /racing\s*princess/i,
  },
  {
    id: 'birthday-idol',
    name: 'Birthday Idol',
    nameJa: 'バースデーアイドル',
    url: 'https://www.ironmousemodelindex.com/model0020',
    pattern: /birthday\s*idol/i,
  },
  {
    id: 'wonderland-reject',
    name: 'Wonderland Reject',
    nameJa: 'ワンダーランドリジェクト',
    url: 'https://www.ironmousemodelindex.com/model0019',
    pattern: /wonderland\s*reject/i,
  },
  {
    id: 'underworld-goddess',
    name: 'Underworld Goddess',
    nameJa: '冥界の女神',
    url: 'https://www.ironmousemodelindex.com/model0018',
    pattern: /underworld\s*goddess/i,
  },
  {
    id: 'pink-rock',
    name: 'Pink Rock',
    nameJa: 'ピンクロック',
    url: 'https://www.ironmousemodelindex.com/model0017',
    pattern: /pink\s*rock/i,
  },
  {
    id: 'demon-princess',
    name: 'Demon Princess',
    nameJa: 'デーモンプリンセス',
    url: 'https://www.ironmousemodelindex.com/model0016',
    pattern: /demon\s*princess/i,
  },
  {
    id: 'season-2-vrc-3d',
    name: 'Season 2 VRC 3D',
    nameJa: 'シーズン2VRC3D',
    url: 'https://www.ironmousemodelindex.com/model0015',
    pattern: /season\s*2\s*vrc\s*3d/i,
  },
  {
    id: 'angel-form',
    name: 'Angel Form',
    nameJa: '天使形態',
    url: 'https://www.ironmousemodelindex.com/model0014',
    pattern: /angel\s*form/i,
  },
  {
    id: 'vills-idol',
    name: 'Vills Idol',
    nameJa: 'ヴィルズアイドル',
    url: 'https://www.ironmousemodelindex.com/model0013',
    pattern: /vills\s*idol/i,
  },
  {
    id: 'demon-christmas',
    name: 'Demon Christmas',
    nameJa: 'デーモンクリスマス',
    url: 'https://www.ironmousemodelindex.com/model0012',
    pattern: /demon\s*christmas/i,
  },
  {
    id: 'demon-queen-3d',
    name: 'Demon Queen 3D',
    nameJa: 'デーモンクイーン3D',
    url: 'https://www.ironmousemodelindex.com/model0011',
    pattern: /demon\s*queen\s*3d/i,
  },
  {
    id: 'angel-mouse',
    name: 'Angel Mouse',
    nameJa: 'エンジェルマウス',
    url: 'https://www.ironmousemodelindex.com/model0010',
    pattern: /angel\s*mouse/i,
  },
  {
    id: 'season-2-idol',
    name: 'Season 2 Idol',
    nameJa: 'シーズン2アイドル',
    url: 'https://www.ironmousemodelindex.com/model0009',
    pattern: /season\s*2\s*idol/i,
  },
  {
    id: 'swimsuit-3d',
    name: 'Swimsuit 3D',
    nameJa: '水着3D',
    url: 'https://www.ironmousemodelindex.com/model0008',
    pattern: /swimsuit\s*3d/i,
  },
  {
    id: 'demon-queen',
    name: 'Demon Queen',
    nameJa: 'デーモンクイーン',
    url: 'https://www.ironmousemodelindex.com/model0007',
    pattern: /demon\s*queen(?!\s*3d)/i,
  },
  {
    id: 'season-2-3d',
    name: 'Season 2 3D',
    nameJa: 'シーズン23D',
    url: 'https://www.ironmousemodelindex.com/model0006',
    pattern: /season\s*2\s*3d/i,
  },
  {
    id: 'season-2',
    name: 'Season 2',
    nameJa: 'シーズン2',
    url: 'https://www.ironmousemodelindex.com/model0005',
    pattern: /season\s*2(?!\s*3d|.*idol|.*vrc)/i,
  },
  // -------------------------
  // OTHER MODELS
  // -------------------------
  {
    id: 'worm-mouse',
    name: 'Worm Mouse',
    nameJa: 'ワームマウス',
    url: 'https://www.ironmousemodelindex.com/modelo005',
    pattern: /worm\s*mouse/i,
  },
  {
    id: 'gremlin-brat-wonderland',
    name: 'Gremlin BratWonderland',
    nameJa: 'グレムリン・ブラットワンダーランド',
    url: 'https://www.ironmousemodelindex.com/modelo016',
    pattern: /gremlin\s*brat/i,
  },
  {
    id: 'gremlin-decora-witch',
    name: 'Gremlin DecoraWitch',
    nameJa: 'グレムリン・デコラウィッチ',
    url: 'https://www.ironmousemodelindex.com/modelo015',
    pattern: /gremlin\s*decora/i,
  },
  {
    id: 'plushie-mouse-s2',
    name: 'Plushie Mouse S2',
    nameJa: 'ぬいぐるみマウスS2',
    url: 'https://www.ironmousemodelindex.com/modelo017',
    pattern: /plushie\s*mouse\s*(s2|season\s*2)/i,
  },
  {
    id: 'scuffed-mouse',
    name: 'Scuffed Mouse',
    nameJa: 'スカフドマウス',
    url: 'https://www.ironmousemodelindex.com/modelo002',
    pattern: /scuffed\s*mouse/i,
  },
  {
    id: 'hotdog-mouse',
    name: 'Hotdog Mouse',
    nameJa: 'ホットドッグマウス',
    url: 'https://www.ironmousemodelindex.com/modelo017',
    pattern: /hot\s*dog\s*mouse|hotdog\s*mouse/i,
  },
];
