import type { DataPattern } from './types';

export const POKEMON_PATTERNS: DataPattern[] = [
  { name: 'Arcanine', nameJa: 'ウインディ', id: 'arcanine', pattern: /\barcanine\b/i },
  { name: 'Bellsprout', nameJa: 'マダツボミ', id: 'bellsprout', pattern: /\bbellsprout\b/i },
  { name: 'Bulbasaur', nameJa: 'フシギダネ', id: 'bulbasaur', pattern: /\bbulbasaur\b/i },
  { name: 'Charizard', nameJa: 'リザードン', id: 'charizard', pattern: /\bcharizard\b/i },
  { name: 'Charmander', nameJa: 'ヒトカゲ', id: 'charmander', pattern: /\bcharmander\b/i },
  { name: 'Clefairy', nameJa: 'ピッピ', id: 'clefairy', pattern: /\bclefairy\b/i },
  { name: 'Cubone', nameJa: 'カラカラ', id: 'cubone', pattern: /\bcubone\b/i },
  { name: 'Dragonair', nameJa: 'ハクリュー', id: 'dragonair', pattern: /\bdragonair\b/i },
  { name: 'Dragonite', nameJa: 'カイリュー', id: 'dragonite', pattern: /\bdragonite\b/i },
  { name: 'Dreepy', nameJa: 'ドラメシヤ', id: 'dreepy', pattern: /\bdreepy\b/i },
  { name: 'Eevee', nameJa: 'イーブイ', id: 'eevee', pattern: /\beevee\b/i },
  { name: 'Gardevoir', nameJa: 'サーナイト', id: 'gardevoir', pattern: /\bgardevoir\b/i },
  { name: 'Gengar', nameJa: 'ゲンガー', id: 'gengar', pattern: /\bgengar\b/i },
  { name: 'Gogoat', nameJa: 'ゴーゴート', id: 'gogoat', pattern: /\bgogoat\b/i },
  { name: 'Greninja', nameJa: 'ゲッコウガ', id: 'greninja', pattern: /\bgreninja\b/i },
  { name: 'Haunter', nameJa: 'ゴースト', id: 'haunter', pattern: /\bhaunter\b/i },
  { name: 'Lapras', nameJa: 'ラプラス', id: 'lapras', pattern: /\blapras\b/i },
  { name: 'Lucario', nameJa: 'ルカリオ', id: 'lucario', pattern: /\blucario\b/i },
  { name: 'Machamp', nameJa: 'カイリキー', id: 'machamp', pattern: /\bmachamp\b/i },
  { name: 'Meowth', nameJa: 'ニャース', id: 'meowth', pattern: /\bmeowth\b/i },
  { name: 'Mew', nameJa: 'ミュウ', id: 'mew', pattern: /\bmew\b/i },
  { name: 'Mewtwo', nameJa: 'ミュウツー', id: 'mewtwo', pattern: /\bmewtwo\b/i },
  { name: 'Mr. Mime', nameJa: 'バリヤード', id: 'mr-mime', pattern: /\bmr\.?\s?mime\b/i },
  { name: 'Nidoking', nameJa: 'ニドキング', id: 'nidoking', pattern: /\bnidoking\b/i },
  { name: 'Ninetales', nameJa: 'キュウコン', id: 'ninetales', pattern: /\bninetales\b/i },
  { name: 'Omanyte', nameJa: 'オムナイト', id: 'omanyte', pattern: /\bomanyte\b/i },
  { name: 'Paras', nameJa: 'パラス', id: 'paras', pattern: /\bparas\b/i },
  { name: 'Pikachu', nameJa: 'ピカチュウ', id: 'pikachu', pattern: /\bpikachu\b/i },
  { name: 'Ponyta', nameJa: 'ポニータ', id: 'ponyta', pattern: /\bponyta\b/i },
  { name: 'Psyduck', nameJa: 'コダック', id: 'psyduck', pattern: /\bpsyduck\b/i },
  { name: 'Rattata', nameJa: 'コラッタ', id: 'rattata', pattern: /\brattata\b/i },
  { name: 'Rhydon', nameJa: 'サイドン', id: 'rhydon', pattern: /\brhydon\b/i },
  { name: 'Sandslash', nameJa: 'サンドパン', id: 'sandslash', pattern: /\bsandslash\b/i },
  { name: 'Slowbro', nameJa: 'ヤドラン', id: 'slowbro', pattern: /\bslowbro\b/i },
  { name: 'Slowpoke', nameJa: 'ヤドン', id: 'slowpoke', pattern: /\bslowpoke\b/i },
  { name: 'Snorlax', nameJa: 'カビゴン', id: 'snorlax', pattern: /\bsnorlax\b/i },
  { name: 'Squirtle', nameJa: 'ゼニガメ', id: 'squirtle', pattern: /\bsquirtle\b/i },
  { name: 'Tangela', nameJa: 'モンジャラ', id: 'tangela', pattern: /\btangela\b/i },
  { name: 'Venomoth', nameJa: 'モルフォン', id: 'venomoth', pattern: /\bvenomoth\b/i },
];
