import type { DataPattern } from './types';

export const UMAMUSUME_PATTERNS: DataPattern[] = [
  {
    name: 'Agnes Digital',
    nameJa: 'アグネスデジタル',
    id: 'agnes-digital',
    pattern: /\b(agnes\s*digital|digital)\b/i,
  },
  {
    name: 'Agnes Tachyon',
    nameJa: 'アグネスタキオン',
    id: 'agnes-tachyon',
    pattern: /\b(agnes\s*tachyon|tachyon)\b/i,
  },
  {
    name: 'Admire Vega',
    nameJa: 'アドマイヤベガ',
    id: 'admire-vega',
    pattern: /\b(admire\s*vega|vega)\b/i,
  },
  {
    name: 'Almond Eye',
    nameJa: 'アーモンドアイ',
    id: 'almond-eye',
    pattern: /\b(almond\s*eye|eye)\b/i,
  },
  {
    name: 'Boku no Bakushin O',
    nameJa: 'バクシンオー',
    id: 'boku-no-bakushin-o',
    pattern: /\b(bakushin|bakushin\s*o|boku\s*no\s*bakushin)\b/i,
  },
  {
    name: 'Biwa Hayahide',
    nameJa: 'ビワハヤヒデ',
    id: 'biwa-hayahide',
    pattern: /\b(biwa\s*hayahide)\b/i,
  },
  {
    name: 'Daiwa Scarlet',
    nameJa: 'ダイワスカーレット',
    id: 'daiwa-scarlet',
    pattern: /\b(daiwa\s*scarlet|scarlet)\b/i,
  },
  {
    name: 'Daitaku Helios',
    nameJa: 'ダイタクヘリオス',
    id: 'daitaku-helios',
    pattern: /\b(daitaku\s*helios|helios)\b/i,
  },
  {
    name: 'Eishin Flash',
    nameJa: 'エイシンフラッシュ',
    id: 'eishin-flash',
    pattern: /\b(eishin\s*flash|flash)\b/i,
  },
  {
    name: 'El Condor Pasa',
    nameJa: 'エルコンドルパサー',
    id: 'el-condor-pasa',
    pattern: /\b(el\s*condor\s*pasa|condor)\b/i,
  },
  {
    name: 'Fenomeno',
    nameJa: 'フェノメノ',
    id: 'fenomeno',
    pattern: /\b(fenomeno)\b/i,
  },
  {
    name: 'Grass Wonder',
    nameJa: 'グラスワンダー',
    id: 'grass-wonder',
    pattern: /\b(grass\s*wonder|wonder)\b/i,
  },
  {
    name: 'Gold Ship',
    nameJa: 'ゴールドシップ',
    id: 'gold-ship',
    pattern: /\b(gold\s*ship|goldship)\b/i,
  },
  {
    name: 'Haruka Urara',
    nameJa: 'ハルウララ',
    id: 'haru-urara',
    pattern: /\b(haru\s*urara|urara)\b/i,
  },
  {
    name: 'Kitasan Black',
    nameJa: 'キタサンブラック',
    id: 'kitasan-black',
    pattern: /\b(kitasan\s*black|black)\b/i,
  },
  {
    name: 'Manhattan Cafe',
    nameJa: 'マンハッタンカフェ',
    id: 'manhattan-cafe',
    pattern: /\b(manhattan\s*cafe|cafe)\b/i,
  },
  {
    name: 'Maruzensky',
    nameJa: 'マルゼンスキー',
    id: 'maruzensky',
    pattern: /\b(maruzensky)\b/i,
  },
  {
    name: 'Matikanetannhäuser',
    nameJa: 'マチカネタンホイザ',
    id: 'matikanetannhauser',
    pattern: /\b(matikanetannhauser|tannhauser)\b/i,
  },
  {
    name: 'Mejiro McQueen',
    nameJa: 'メジロマックイーン',
    id: 'mejiro-mcqueen',
    pattern: /\b(mejiro\s*mcqueen|mcqueen)\b/i,
  },
  {
    name: 'Narita Brian',
    nameJa: 'ナリタブライアン',
    id: 'narita-brian',
    pattern: /\b(narita\s*brian|brian)\b/i,
  },
  {
    name: 'Narita Top Road',
    nameJa: 'ナリタトップロード',
    id: 'narita-top-road',
    pattern: /\b(narita\s*top\s*road|top\s*road)\b/i,
  },
  {
    name: 'Nice Nature',
    nameJa: 'ナイスネイチャ',
    id: 'nice-nature',
    pattern: /\b(nice\s*nature|naturenice)\b/i,
  },
  {
    name: 'Oguri Cap',
    nameJa: 'オグリキャップ',
    id: 'oguri-cap',
    pattern: /\b(oguri\s*cap|oguricap)\b/i,
  },
  {
    name: 'Satono Diamond',
    nameJa: 'サトノダイヤモンド',
    id: 'satono-diamond',
    pattern: /\b(satono\s*diamond|diamond)\b/i,
  },
  {
    name: 'Silence Suzuka',
    nameJa: 'サイレンススズカ',
    id: 'silence-suzuka',
    pattern: /\b(silence\s*suzuka|suzuka)\b/i,
  },
  {
    name: 'Special Week',
    nameJa: 'スペシャルウィーク',
    id: 'special-week',
    pattern: /\b(special\s*week|spweek)\b/i,
  },
  {
    name: 'Symboli Rudolf',
    nameJa: 'シンボリルドルフ',
    id: 'symboli-rudolf',
    pattern: /\b(symboli\s*rudolf|rudolf)\b/i,
  },
  {
    name: 'Super Creek',
    nameJa: 'スーパークリーク',
    id: 'super-creek',
    pattern: /\b(super\s*creek|creek)\b/i,
  },
  {
    name: 'Taiki Shuttle',
    nameJa: 'タイキシャトル',
    id: 'taiki-shuttle',
    pattern: /\b(taiki\s*shuttle|shuttle)\b/i,
  },
  {
    name: 'Tanino Gimlet',
    nameJa: 'タニノギムレット',
    id: 'tanino-gimlet',
    pattern: /\b(tanino\s*gimlet|gimlet)\b/i,
  },
  {
    name: 'Tokai Teio',
    nameJa: 'トウカイテイオー',
    id: 'tokai-teio',
    pattern: /\b(tokai\s*teio|teio)\b/i,
  },
  {
    name: 'TM Opera O',
    nameJa: 'テイエムオペラオー',
    id: 'tm-opera-o',
    pattern: /\b(tm\s*opera\s*o|opera\s*o)\b/i,
  },
  {
    name: 'Vodka',
    nameJa: 'ウオッカ',
    id: 'vodka',
    pattern: /\b(vodka)\b/i,
  },
];
